load("//tools/install:install.bzl", "install")

package(
    default_visibility = ["//visibility:public"],
)

#FIXME: No install target yet
# install(
#     name = "install",
#     deps = [
#         "//modules/drivers/camera:install",
#         "//modules/drivers/gnss:install",
#         "//modules/drivers/microphone:install",
#         "//modules/drivers/tools/image_decompress:install",
#     ],
# )
